### ISSUE TITLE
Make IPv4/IPv6 stack tests more useful

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io-modules/device-diagnostics#292]
We added a check for IPv4 and IPv6 stack which just tries to curl services with those protocols. However, this could just add "error fatigue" because this won't actually indicate a problem all the time it just means your IPv4/IPv6 stack doesn't work.

A better case to test for is if the device has an IPv4/IPv6 address and the stack doesn't work.

https://github.com/balena-io-modules/device-diagnostics/blob/310aa74b05ecdd30aebbf180a3455366b01b3f0f/scripts/checks.sh#L312-L313

**Comment by 20k-ultra** [comment]
thoughts @alexgg @klutchell

**Comment by klutchell** [comment]
Agreed that we shouldn't report a broken IPv6 stack unless the device is assigned an IPv6 address and might try to use it.
