### ISSUE TITLE
Diagnostics check_networking test fails on IPv6 only networks.

### ISSUE THREAD

**Issue by ab77** [balena-io-modules/device-diagnostics#298]
## Expected Behaviour
Diagnostics `check_networking` passes on IPv6 only networks by attempting to resolve using public IPv6 DNS (e.g. https://developers.google.com/speed/public-dns/docs/using) instead of hard-coding IPv4 IPs.

## Actual Behaviour
Diagnostics `check_networking` test fails on IPv6 only networks.

![image](https://user-images.githubusercontent.com/2033996/152888135-971357bb-c441-4ab6-b7b2-6b267be9e6e9.png)

## Steps to Reproduce the Problem

1. block IPv4 DHCP traffic (67-68/udp) on a dual IPv4/IPv6 network with public access on both address families
2. provision a device
3. observe actual behaviour

## References
https://jel.ly.fish/brainstorm-topic-c3f8670a-8981-42ae-bcbf-1f57e959122d

**Comment by klutchell** [comment]
This is only somewhat related to the diagnostic script.

When testing DNS resolution we read the upstream servers directly from dnsmasq on the host, and by default in balenaOS we include 8.8.8.8 in the list of IPv4 DNS servers.
https://www.balena.io/docs/reference/OS/configuration/#dnsservers

So in my mind the correct solution is to remove 8.8.8.8 from the server list on balenaOS if IPv4 networking is not available. This can be done by setting `dnsServers="null` in config.json.

OR, we change the diagnostics to report both successful and failed DNS servers so it's clear that the IPv6 servers from DHCP are working.

OR, we change the diagnostics to only report a failure if none of the servers can resolve, but this is removing some helpful context IMO.

**Comment by klutchell** [comment]
Agreed on an arch call brainstorm to change the wording to indicate that some of the servers worked, and only some of the servers failed. Maybe raise a warning instead of an error in this case.

**Comment by myarmolinsky** [comment]
@klutchell Generally when I see an error I don't assume everything is broken, I just start investigating thay individual error. So unless you split up the health check into multiple health checks to display successes and errors, I don't think it is necessary to tell the user which ones were successful. Perhaps that's just me though, definitely interested in @chrisys 's thoughts

**Comment by klutchell** [comment]
@myarmolinsky I think I agree with you. In fact, clicking on the failed test will link you to the documentation describing the test, where I can make it more clear that successful servers are not shown.
https://www.balena.io/docs/reference/diagnostics/#test_upstream_dns
